### ISSUE TITLE
Convenience for reading a single DS18X20 sensor

### ISSUE THREAD

**Issue by amotl** [robert-hh/Onewire_DS18X20#11]
@robert-hh likes to have a convenience functionality for reading a single DS18X20 sensor attached to the 1-Wire bus through a code fragment like
```
if (rom is None) and (len(self.roms) == 1):
    rom = self.roms[0]
```

I am proposing to add this functionality through some kind of adapter class like `DS18X20Single` in order not to clutter the core implementation.

**Comment by amotl** [comment]
I've added the proposed adapter class through the commit de990de2 referenced above. However, it will not convert into a pull request easily as the commit history seems to have been amended on the upstream repository.

**Comment by robert-hh** [comment]
That's obsolete by now.
