### ISSUE TITLE
What does mean "required" in reset()?

### ISSUE THREAD

**Issue by MauroDiamantino** [robert-hh/Onewire_DS18X20#18]
Hi, what is the purpose of the parameter `required` in the method `reset()` of onewire.py?
Does it state that checking the presence pulse after reset is important or nor?

**Comment by robert-hh** [comment]
Exactly what README.md tells: `Resets the bus. If the parameter required is True, AssertError is raised if no device on the bus responds`.

So calling `reset(required=True)` raises an error if no device is detected. Otherwise it silently ignores that state.
