### ISSUE TITLE
Presence-Detect Low time

### ISSUE THREAD

**Issue by MauroDiamantino** [robert-hh/Onewire_DS18X20#19]
Hi, the Presence-Detect Low time in line 47 of onewire.py, should not be 240ms rather than 420ms?
I said that taking into account the DS18B20 Maxim [datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ds18b20.pdf). In page 3, it is stated that the max value for Presence-Detect Low time (tPDLOW) should be 240ms.

**Comment by robert-hh** [comment]
The data sheet just says that the response low pulse of the DS18B20 starts latest after 60µs and is not longer than 240µs. The code probes the bus after 60µs for being low. Then it waits for a while, and that while must be at least 240µs, but is allowed to be longer. Nothing happens in this time.
